version: "3.8"
services:
  node_a:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node_a
    environment:
      - PORT=5000
      - PUBLIC_URL=http://localhost:5000
      - FRAGMENTS_DIR=/data/fragments
    volumes:
      - ./node/fragments_a:/data/fragments
      - ./node:/app:ro
    ports:
      - "5000:5000"
    networks:
      - p2pnet

  node_b:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node_b
    environment:
      - PORT=5000
      - PUBLIC_URL=http://localhost:5001
      - FRAGMENTS_DIR=/data/fragments
    volumes:
      - ./node/fragments_b:/data/fragments
      - ./node:/app:ro
    ports:
      - "5001:5000"
    networks:
      - p2pnet

networks:
  p2pnet:
    driver: bridge
